env:
  - VERSION=1.1.54380
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
cache: pip
services:
  - docker
before_install:
  - docker run -d -p 127.0.0.1:9000:9000 --name test-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:$VERSION
  - docker ps -a
  # Overriding setup.cfg. Set host=clickhouse-server
  - sed -i 's/^host=localhost$/host=clickhouse-server/' setup.cfg
  # Make host think that clickhouse-server is localhost
  - echo '127.0.0.1 clickhouse-server' | sudo tee /etc/hosts > /dev/null
install:
  - pip install --upgrade pip setuptools
  - pip install flake8 flake8-print coveralls
before_script:
  flake8
script:
  coverage run --source=clickhouse_sqlalchemy setup.py test
after_success:
  coveralls
